Update cluster5.cfg
InZidiuZ/op-framework-public pull request #103
Opened 2021-12-06 22:42 UTC by Enryy

I don't know if I wrote it correctly, but I would like to remove the radios from the tool shop... if it's not written correctly, tell me how to fix it

2021-12-07 18:43 UTC, InZidiuZ requested changes

2021-12-07 18:43 UTC, InZidiuZ commented on configs/cluster5.cfg
> +store_overrides = "gun_store=pistol_ammo:42,sub_ammo:69;grocery_store=water:8;tool_shop=removeradio"
...wut?

2021-12-07 18:45 UTC, Enryy commented on configs/cluster5.cfg
> +store_overrides = "gun_store=pistol_ammo:42,sub_ammo:69;grocery_store=water:8;tool_shop=removeradio"
As I wrote in the description, how can I remove an item from a shop? Is it possible to do this or can I just change the prices?

2021-12-07 18:46 UTC, InZidiuZ commented on configs/cluster5.cfg
> +store_overrides = "gun_store=pistol_ammo:42,sub_ammo:69;grocery_store=water:8;tool_shop=removeradio"
You can only change and add items.

2021-12-07 18:48 UTC, Enryy commented on configs/cluster5.cfg
> +store_overrides = "gun_store=pistol_ammo:42,sub_ammo:69;grocery_store=water:8;tool_shop=removeradio"
ah ok, could you give me an example of how to change an item

for example if I want to change pigeon's milk to radio

2021-12-07 19:36 UTC, InZidiuZ commented on configs/cluster5.cfg
> +store_overrides = "gun_store=pistol_ammo:42,sub_ammo:69;grocery_store=water:8;tool_shop=removeradio"
You can change an already-existing item and have a new price set. Not change it to another item.

2021-12-09 19:01 UTC, InZidiuZ approved these changes

2021-12-09 19:01 UTC, merged