Update it-IT.lua
InZidiuZ/op-framework-public pull request #105
Opened 2021-12-08 17:02 UTC by Enryy

Added DNA, frisk, fingerpint etc...

2021-12-08 17:06 UTC, InZidiuZ requested changes

2021-12-08 17:06 UTC, InZidiuZ commented on languages/it-IT.lua
> +
Random newline?

2021-12-08 17:06 UTC, InZidiuZ commented on languages/it-IT.lua
> +
Random newline?

2021-12-08 17:06 UTC, InZidiuZ commented on languages/it-IT.lua
> +
RANDOM NEWLINE?

2021-12-11 17:55 UTC, InZidiuZ requested changes

2021-12-11 17:55 UTC, InZidiuZ commented on languages/it-IT.lua
> +		phone_description = "Usalo per chiamare qualche tuo amico",
Translations should not go against their original meaning. A locale should have the exact same meaning in all languages as it should be possible for anyone playing on any server to change their language without it causing confusion.

2021-12-11 18:01 UTC, Enryy commented on languages/it-IT.lua
> +		phone_description = "Usalo per chiamare qualche tuo amico",
ahhhhh ok, I have translated correctly now

2021-12-11 19:46 UTC, InZidiuZ commented
You still have random newlines in the PR as I mentioned earlier. This won't be merged until that is fixed.

2021-12-12 14:35 UTC, Enryy commented
It should be fine now

2021-12-12 14:40 UTC, InZidiuZ commented
...what? You just re-introduced a change I said wasn't permitted.

2021-12-12 14:42 UTC, Enryy commented
I have edited and copied the old file, sorry my mistake

2021-12-12 14:45 UTC, merged