Update es-MX.lua
InZidiuZ/op-framework-public pull request #126
Opened 2022-01-22 23:11 UTC by KidDano

2022-01-25 20:11 UTC, InZidiuZ requested changes
You have a lot of bad spacing here & also a lot of missing translations.

2022-01-26 02:06 UTC, InZidiuZ commented
Almost

2022-01-26 21:25 UTC, InZidiuZ commented
No

2022-01-26 22:29 UTC, closed without merging

2022-01-26 22:29 UTC, KidDano commented
Sending a new one