languages/en-GB - Add missing keys
InZidiuZ/op-framework-public pull request #373
Opened 2023-02-11 21:20 UTC by CloudTheWolf

2023-02-12 14:16 UTC, InZidiuZ requested changes
I'll update the main language file so you can add all the new ones there instead of just trying to find them from 'missing locales' in-game

2023-02-12 14:16 UTC, InZidiuZ commented on languages/en-GB.lua
> +
Two new-lines?! Are you insane????

2023-02-12 14:28 UTC, CloudTheWolf commented
> I'll update the main language file so you can add all the new ones there instead of just trying to find them from 'missing locales' in-game

Thanks I'll get these added now

2023-02-12 14:44 UTC, coalaura commented on languages/en-GB.lua
> +
This is mayhem

2023-02-12 14:49 UTC, CloudTheWolf commented on languages/en-GB.lua
> +
Fixed!

2023-02-13 14:52 UTC, InZidiuZ approved these changes

2023-02-13 14:53 UTC, merged