Update pl-PL.lua
InZidiuZ/op-framework-public pull request #475
Opened 2023-06-23 19:14 UTC by callmeeJeff

2023-06-23 19:52 UTC, InZidiuZ requested changes
Messy PR, please clean up. I got to 17 comments, but I am not going to spend time finding all of the bad parts.

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +	floatSeperator = ".", -- with it set as ".", (25 + (1/5)) -> 25.2
Why are you changing these?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +		delete_vehicle_command_parameter_ignore_heading = "yes",
'yes'?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 19:52 UTC, InZidiuZ commented on languages/pl-PL.lua
> +
?

2023-06-23 21:42 UTC, callmeeJeff commented
I guess all fixed

2023-06-23 23:46 UTC, callmeeJeff commented
Idk what i need to do more

2023-06-24 09:52 UTC, InZidiuZ approved these changes

2023-06-24 09:52 UTC, InZidiuZ commented
These will be added with the nest auto-locales.

2023-06-24 09:52 UTC, closed without merging