Update it-IT.lua
InZidiuZ/op-framework-public pull request #99
Opened 2021-11-26 15:05 UTC by Enryy

2021-11-26 18:48 UTC, InZidiuZ requested changes
Looking very good!

2021-11-26 18:48 UTC, InZidiuZ commented on languages/it-IT.lua
> +	    set_body_armor_command = "/set_body_armor",
Bad tabbing

2021-11-26 18:48 UTC, InZidiuZ commented on languages/it-IT.lua
> +		server_is_starting = "In attesa dell'avvio del server    ...",
Why are there a bunch of spaces here?

2021-11-26 18:48 UTC, InZidiuZ commented on languages/it-IT.lua
> +		no = "No"
Were these two left out intentionally?

2021-11-26 18:56 UTC, Enryy commented on languages/it-IT.lua
> +	    set_body_armor_command = "/set_body_armor",
Precisely which string should I adjust?

2021-11-27 01:54 UTC, Enryy commented
I should have solved it, let me know

2021-11-27 15:47 UTC, Enryy commented
Did you get the changes I made?

2021-11-27 15:48 UTC, InZidiuZ commented
Not all...

2021-12-02 15:26 UTC, InZidiuZ requested changes

2021-12-02 15:26 UTC, InZidiuZ commented on languages/it-IT.lua
> +    }
Bad spacing

2021-12-03 01:16 UTC, Enryy commented on languages/it-IT.lua
> +	    set_body_armor_command = "/set_body_armor",
by for bad tabbing you mean that /set_body_armor_command happens in the wrong line right?

2021-12-03 16:34 UTC, InZidiuZ commented on languages/it-IT.lua
> +	    set_body_armor_command = "/set_body_armor",
You use spaces instead of tabs and it's also not aligned with the other entries as it should be.

2021-12-04 17:04 UTC, InZidiuZ commented
I ran the file through checks and found these irregularities:
```
"  " @ it-IT.lua:236
"  " @ it-IT.lua:312
"  " @ it-IT.lua:1501
"  " @ it-IT.lua:1888
"  " @ it-IT.lua:1889
"  " @ it-IT.lua:1892
"  " @ it-IT.lua:2071
"  " @ it-IT.lua:2372
"  " @ it-IT.lua:3087
"  " @ it-IT.lua:3352
"  " @ it-IT.lua:3488
"  " @ it-IT.lua:3980
"  " @ it-IT.lua:4257

Not cool occurrences found: 14
```

2021-12-05 15:52 UTC, Enryy commented
I should have solved it now

2021-12-07 18:46 UTC, InZidiuZ commented
You didn't even make any changes to the lines I commented on...

2021-12-07 19:35 UTC, InZidiuZ approved these changes
Finally!

2021-12-07 19:35 UTC, merged